# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/produc_ms
    username: postgres
    password: 1111
  # JPA properties
  jpa:
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

# Port
server:
  port: 8082

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui
